#!/usr/bin/env python3
"""Rewrite the FEED block in README.md from the YouTube, Medium and Substack feeds.

Standard library only — no pip install, no third-party action holding write access
to the profile README.
"""

import re
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ElementTree
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

README = Path(__file__).resolve().parent.parent / "README.md"

YOUTUBE_FEED = "https://www.youtube.com/feeds/videos.xml?channel_id=UCOjAXiOifsFuMYZimCgrsnQ"
BLOG_FEEDS = [
    ("Medium", "https://medium.com/feed/@dancanian25"),
    ("Substack", "https://yourjavaguy.substack.com/feed"),
]

ATOM = "{http://www.w3.org/2005/Atom}"
START = "<!-- FEED:START -->"
END = "<!-- FEED:END -->"
MAX_VIDEOS = 3
MAX_POSTS = 3

# Medium and Substack reject urllib's default User-Agent.
USER_AGENT = "Mozilla/5.0 (compatible; your-javaguy-profile-bot/1.0; +https://github.com/Dancan254)"


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def parse_youtube(raw):
    root = ElementTree.fromstring(raw)
    entries = []
    for entry in root.findall(f"{ATOM}entry"):
        title = entry.findtext(f"{ATOM}title", "").strip()
        link = entry.find(f"{ATOM}link")
        published = entry.findtext(f"{ATOM}published", "").strip()
        if not (title and link is not None and published):
            continue
        entries.append(
            {
                "title": title,
                "url": link.get("href"),
                "date": datetime.fromisoformat(published).astimezone(timezone.utc),
            }
        )
    return entries


def parse_rss(raw, source):
    root = ElementTree.fromstring(raw)
    entries = []
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        url = (item.findtext("link") or "").strip()
        published = (item.findtext("pubDate") or "").strip()
        if not (title and url and published):
            continue
        entries.append(
            {
                "title": title,
                "url": url,
                "source": source,
                "date": parsedate_to_datetime(published).astimezone(timezone.utc),
            }
        )
    return entries


def newest(entries, limit):
    return sorted(entries, key=lambda entry: entry["date"], reverse=True)[:limit]


def render(videos, posts):
    lines = [
        START,
        "<!-- Generated by scripts/update_feed.py — edits here are overwritten daily. -->",
        "",
        "**▸ Latest from the channel**",
        "",
    ]
    for video in videos:
        lines.append(f"- [{video['title']}]({video['url']}) · `{video['date']:%Y-%m-%d}`")
    lines += ["", "**▸ Latest writing**", ""]
    for post in posts:
        lines.append(
            f"- [{post['title']}]({post['url']}) · `{post['source']}` · `{post['date']:%Y-%m-%d}`"
        )
    lines += ["", END]
    return "\n".join(lines)


def main():
    try:
        videos = newest(parse_youtube(fetch(YOUTUBE_FEED)), MAX_VIDEOS)
        posts = []
        for source, url in BLOG_FEEDS:
            posts += parse_rss(fetch(url), source)
        posts = newest(posts, MAX_POSTS)
    except (urllib.error.URLError, ElementTree.ParseError, ValueError, OSError) as error:
        # Never half-write the block — a transient feed outage leaves the last good content.
        print(f"feed fetch failed, README untouched: {error}", file=sys.stderr)
        return 1

    if not videos or not posts:
        print("a feed returned no usable entries, README untouched", file=sys.stderr)
        return 1

    readme = README.read_text(encoding="utf-8")
    if START not in readme or END not in readme:
        print(f"markers {START} / {END} not found in README", file=sys.stderr)
        return 1

    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: render(videos, posts),
        readme,
        flags=re.DOTALL,
    )

    if updated == readme:
        print("feed unchanged")
        return 0

    README.write_text(updated, encoding="utf-8")
    print("feed updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
